import Head from 'next/head'
import Slider from '../components/Sections/Slider'
import About from '../components/Sections/About'
import Works from '../components/Sections/Works';
import Blog from '../components/Sections/Blog';
import Connect from '../components/Sections/Connect';
import Layout from '../components/Layout/Layout';

type Props = {}

export default function Home({}: Props) {
  return (
    <Layout>
      <Head>
        <title>Emre Karadağ Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Slider />
      <About />
      <Works />
      <Blog />
      <Connect />
    </Layout>
  )
}
